-- liquibase formatted sql
CREATE TABLE account
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    type VARCHAR(10),
    balance NUMERIC CHECK(balance >= 0),
    client_id BIGINT REFERENCES client(id)
);

CREATE TABLE transaction
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    amount NUMERIC CHECK(amount >= 0),
    created_at TIMESTAMP,
    account_id BIGINT REFERENCES account(id)
);

CREATE TABLE data_source_error_log
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    stack_trace_text VARCHAR NOT NULL,
    message VARCHAR NOT NULL,
    method_signature VARCHAR NOT NULL
);